export const LYOVA_TABS=Object.freeze([{id:'chat',route:'lyova.chat',label:'Чат'},{id:'recommendations',route:'lyova.recommendations',label:'Рекомендации'},{id:'history',route:'lyova.history',label:'История'},{id:'actions',route:'lyova.actions',label:'Действия'}]);
export const LYOVA_RECOMMENDATIONS=Object.freeze([{id:'path',title:'Продолжить Путь',route:'path.home'},{id:'events',title:'Посмотреть мероприятия',route:'events.list'},{id:'widgets',title:'Открыть инструменты',route:'widgets.home'}]);
export const LYOVA_ACTIONS=Object.freeze([{id:'plan-day',title:'Собрать план дня',effect:'Создание задач и расписания'},{id:'note',title:'Сохранить мысль',effect:'Запись в личные заметки'}]);

export class LyovaSession{
  constructor(runtime=null){this.runtime=runtime;this.messages=[];this.state='idle';this.error=null;}
  async send(text,context={}){const value=String(text||'').trim();if(!value)return null;const message=Object.freeze({id:`local-${this.messages.length+1}`,role:'user',text:value,persisted:false});this.messages.push(message);if(typeof this.runtime?.reply!=='function'){this.state='disabled';return Object.freeze({message,reply:null,persisted:false});}this.state='working';try{const result=await this.runtime.reply({text:value,...context});if(!result?.confirmed||!result.reply)throw Object.assign(new Error('AI reply was not confirmed'),{code:'lyova-reply-unconfirmed'});const reply=Object.freeze({id:String(result.id||`reply-${this.messages.length+1}`),role:'assistant',text:String(result.reply),persisted:Boolean(result.persisted)});this.messages.push(reply);this.state='succeeded';return Object.freeze({message,reply,persisted:reply.persisted});}catch(error){this.state='failed';this.error=error;throw error;}}
}

export function createLyovaActionRepository(adapter=null){const ready=typeof adapter?.execute==='function';return Object.freeze({capabilities:Object.freeze({actions:ready}),async execute(context){if(!ready)throw Object.assign(new Error('Lyova actions require an approved runtime'),{code:'lyova-actions-disabled'});const result=await adapter.execute(context);if(!result?.confirmed)throw Object.assign(new Error('Lyova action was not confirmed'),{code:'lyova-action-unconfirmed'});return Object.freeze({confirmed:true,result:result.result||null});}});}
